DROP TYPE IF EXISTS player_status;
CREATE TYPE player_status AS ENUM (
  'Judge',
  'Player'
);

CREATE TABLE IF NOT EXISTS players (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    player_name TEXT NOT NULL,
    points TEXT DEFAULT '0',
    player_status player_status NOT NULL,
    answer_submitted TEXT
);