DROP TYPE IF EXISTS card_type;
CREATE TYPE card_type AS ENUM (
  'Wild',
  'Regular'
);

DROP TYPE IF EXISTS card_status;
CREATE TYPE card_status AS ENUM (
  'Active',
  'Drawn',
  'Not Drawn'
);

CREATE TABLE IF NOT EXISTS cards (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    card_type card_type NOT NULL,
    card_copy TEXT NOT NULL,
    card_status card_status NOT NULL,
    thread_count INTEGER NOT NULL,
    message_count INTEGER NOT NULL
);

INSERT INTO cards(id,card_type,card_copy,card_status,thread_count,message_count) VALUES (1,'Regular','Someone spills hot oil on you, you scream...','Not Drawn',1,2);
INSERT INTO cards(id,card_type,card_copy,card_status,thread_count,message_count) VALUES (2,'Regular','You arrive at the emergency room, they ask why you''re here. You calmly say…','Not Drawn',11,6);
INSERT INTO cards(id,card_type,card_copy,card_status,thread_count,message_count) VALUES (3,'Regular','You meet your tinder match, they look at you and say…','Not Drawn',8,12);
INSERT INTO cards(id,card_type,card_copy,card_status,thread_count,message_count) VALUES (4,'Regular','You''re waiting to hear about your newly born baby, the doctor comes out and says…','Not Drawn',4,1);
INSERT INTO cards(id,card_type,card_copy,card_status,thread_count,message_count) VALUES (5,'Regular','You ask siri where the nearest coffee shop is, she replies…','Not Drawn',3,4);
INSERT INTO cards(id,card_type,card_copy,card_status,thread_count,message_count) VALUES (6,'Regular','You ask your crush to be exclusive, they reply…','Not Drawn',7,9);
INSERT INTO cards(id,card_type,card_copy,card_status,thread_count,message_count) VALUES (7,'Regular','Suspicious you ask your mom if you are adopted, she whispers…','Not Drawn',1,10);
INSERT INTO cards(id,card_type,card_copy,card_status,thread_count,message_count) VALUES (NULL,NULL,'You have the winning Powerball numbers you exclaim…',NULL,3,8);
INSERT INTO cards(id,card_type,card_copy,card_status,thread_count,message_count) VALUES (NULL,NULL,'Seeing you for the first time after reconstrcutive surgery, your friend gasps and says',NULL,5,2);
INSERT INTO cards(id,card_type,card_copy,card_status,thread_count,message_count) VALUES (NULL,NULL,'Aliens land on Earth, their message to the world is:',NULL,10,3);
INSERT INTO cards(id,card_type,card_copy,card_status,thread_count,message_count) VALUES (NULL,NULL,'I love you, you love me…',NULL,12,11);
INSERT INTO cards(id,card_type,card_copy,card_status,thread_count,message_count) VALUES (NULL,NULL,'You receive a text from yourself 10 years from now. It says:',NULL,2,4);
INSERT INTO cards(id,card_type,card_copy,card_status,thread_count,message_count) VALUES (NULL,NULL,'Hitting on someone at a bar, you start by saying:',NULL,9,11);
INSERT INTO cards(id,card_type,card_copy,card_status,thread_count,message_count) VALUES (NULL,NULL,'First day of work, introduced to the person you''ll share a cubicle with, they look at you and say',NULL,4,9);
INSERT INTO cards(id,card_type,card_copy,card_status,thread_count,message_count) VALUES (NULL,NULL,'I had a dream that:',NULL,10,7);
INSERT INTO cards(id,card_type,card_copy,card_status,thread_count,message_count) VALUES (NULL,NULL,'You text the babysitter to check on your kids. They reply:',NULL,9,3);
INSERT INTO cards(id,card_type,card_copy,card_status,thread_count,message_count) VALUES (NULL,NULL,'You see the grand canyon and exclaim:',NULL,7,8);
INSERT INTO cards(id,card_type,card_copy,card_status,thread_count,message_count) VALUES (NULL,NULL,'Stranded on an island with a stranger, they grab you and say:',NULL,1,6);
INSERT INTO cards(id,card_type,card_copy,card_status,thread_count,message_count) VALUES (NULL,NULL,'After kissing your soul mate for the first time, they look at you and say:',NULL,10,1);
INSERT INTO cards(id,card_type,card_copy,card_status,thread_count,message_count) VALUES (NULL,NULL,'Your wifi network password is…',NULL,4,9);
INSERT INTO cards(id,card_type,card_copy,card_status,thread_count,message_count) VALUES (NULL,NULL,'Seeing your favorite celebrity, you run up to them and say:',NULL,7,10);
INSERT INTO cards(id,card_type,card_copy,card_status,thread_count,message_count) VALUES (NULL,NULL,'After passing through the body scanner at the airport, the TSA agent looks at you and says:',NULL,3,6);
INSERT INTO cards(id,card_type,card_copy,card_status,thread_count,message_count) VALUES (NULL,NULL,'You ask your significant other, "How do I look?" They respond:',NULL,2,9);
INSERT INTO cards(id,card_type,card_copy,card_status,thread_count,message_count) VALUES (NULL,NULL,'Four score and seven years ago…',NULL,12,1);
INSERT INTO cards(id,card_type,card_copy,card_status,thread_count,message_count) VALUES (NULL,NULL,'During a routine physical, your doctor says to you:',NULL,5,8);
INSERT INTO cards(id,card_type,card_copy,card_status,thread_count,message_count) VALUES (NULL,NULL,'Your 5 year old asks if God is real. You answer…',NULL,1,4);
INSERT INTO cards(id,card_type,card_copy,card_status,thread_count,message_count) VALUES (NULL,NULL,'Whenever your parrot meets someone new, it squawks:',NULL,7,5);
INSERT INTO cards(id,card_type,card_copy,card_status,thread_count,message_count) VALUES (NULL,NULL,'A 5 yeaar-old appears lost. After offering to help them, they calmly reply:',NULL,1,5);
INSERT INTO cards(id,card_type,card_copy,card_status,thread_count,message_count) VALUES (NULL,NULL,'Your sitcom catchphrase is:',NULL,7,3);
INSERT INTO cards(id,card_type,card_copy,card_status,thread_count,message_count) VALUES (NULL,NULL,'Your grandmother texts you for the first time:',NULL,4,3);
INSERT INTO cards(id,card_type,card_copy,card_status,thread_count,message_count) VALUES (NULL,NULL,'The dolphin''s first message to humanity is:',NULL,8,12);
INSERT INTO cards(id,card_type,card_copy,card_status,thread_count,message_count) VALUES (NULL,NULL,'You startup your phone for the first time, the following messages is displayed',NULL,7,2);
INSERT INTO cards(id,card_type,card_copy,card_status,thread_count,message_count) VALUES (NULL,NULL,'You have Tourette''s. Periodically you call out:',NULL,1,2);
INSERT INTO cards(id,card_type,card_copy,card_status,thread_count,message_count) VALUES (NULL,NULL,'Your FB memory from 5 years ago says:',NULL,6,9);
INSERT INTO cards(id,card_type,card_copy,card_status,thread_count,message_count) VALUES (NULL,NULL,'On the day of your arranged marriage, you lift the veil and say:',NULL,11,6);
INSERT INTO cards(id,card_type,card_copy,card_status,thread_count,message_count) VALUES (NULL,NULL,'The first words of your autobiography are:',NULL,8,10);
INSERT INTO cards(id,card_type,card_copy,card_status,thread_count,message_count) VALUES (NULL,NULL,'Your best friend is reading your eulogy. There first words are:',NULL,11,7);
INSERT INTO cards(id,card_type,card_copy,card_status,thread_count,message_count) VALUES (NULL,NULL,'You''re the captain of the Titanic. The last words to your crew are:',NULL,5,2);
INSERT INTO cards(id,card_type,card_copy,card_status,thread_count,message_count) VALUES (NULL,NULL,'The voivces in your head keep repeating:',NULL,3,8);
INSERT INTO cards(id,card_type,card_copy,card_status,thread_count,message_count) VALUES (NULL,NULL,'Your family crest says:',NULL,6,10);
INSERT INTO cards(id,card_type,card_copy,card_status,thread_count,message_count) VALUES (NULL,NULL,'The birthday card your grandma sent to you says:',NULL,3,1);
INSERT INTO cards(id,card_type,card_copy,card_status,thread_count,message_count) VALUES (NULL,NULL,'Your final words',NULL,8,2);
INSERT INTO cards(id,card_type,card_copy,card_status,thread_count,message_count) VALUES (NULL,NULL,'You send back your dish at a restaurant, the chef comes out and says:',NULL,2,4);

