DROP TYPE IF EXISTS card_type;
CREATE TYPE card_type AS ENUM (
  'Wild',
  'Regular'
);

DROP TYPE IF EXISTS card_status;
CREATE TYPE card_status AS ENUM (
  'Active',
  'Drawn',
  'Not Drawn'
);

CREATE TABLE IF NOT EXISTS cards (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    card_type card_type NOT NULL,
    card_copy TEXT NOT NULL,
    card_status card_status NOT NULL,
    thread_count INTEGER NOT NULL,
    card_count INTEGER NOT NULL
);