ALTER TABLE IF EXISTS game
  ADD COLUMN IF NOT EXISTS player_ids INTEGER REFERENCES players(id);

ALTER TABLE IF EXISTS game
  ADD COLUMN IF NOT EXISTS active_card INTEGER REFERENCES cards(id);

ALTER TABLE IF EXISTS game
  ADD COLUMN IF NOT EXISTS active_wild_card INTEGER REFERENCES cards(id);
  
ALTER TABLE IF EXISTS players
  ADD COLUMN IF NOT EXISTS game_id INTEGER REFERENCES game(id);

ALTER TABLE IF EXISTS messages
  ADD COLUMN IF NOT EXISTS player_id INTEGER REFERENCES players(id);