ALTER TABLE IF EXISTS game
  DROP COLUMN IF EXISTS player_ids;

ALTER TABLE IF EXISTS game
  DROP COLUMN IF EXISTS active_card;

ALTER TABLE IF EXISTS game
  DROP COLUMN IF EXISTS active_wild_card;

ALTER TABLE IF EXISTS game
  DROP COLUMN IF EXISTS cards_played;
  
ALTER TABLE IF EXISTS players
  DROP COLUMN IF EXISTS game_id;

ALTER TABLE IF EXISTS messages
  DROP COLUMN IF EXISTS player_id;

ALTER TABLE IF EXISTS messages
  DROP COLUMN IF EXISTS game_id;

ALTER TABLE IF EXISTS answers
  DROP COLUMN IF EXISTS game_id;

ALTER TABLE IF EXISTS answers
  DROP COLUMN IF EXISTS player_id;

ALTER TABLE IF EXISTS game
  DROP COLUMN IF EXISTS current_judge;
